export interface DrugInteraction {
  drug: string;
  severity: "mild" | "moderate" | "severe" | "contraindicated";
  effect: string;
}

export interface Drug {
  name: string;
  genericName: string;
  class: string;
  indications: string[];
  contraindications: string[];
  interactions: DrugInteraction[];
  renalDosing: boolean;
  hepaticDosing: boolean;
  sideEffects: string[];
}

export const MOCK_DRUGS: Drug[] = [
  {
    name: "metformin",
    genericName: "metformin hydrochloride",
    class: "Biguanide",
    indications: ["type 2 diabetes mellitus", "PCOS", "prediabetes"],
    contraindications: ["eGFR <30", "metabolic acidosis", "severe hepatic impairment"],
    interactions: [
      { drug: "iodine contrast", severity: "severe", effect: "Risk of lactic acidosis; hold metformin 48h after contrast" },
      { drug: "alcohol", severity: "moderate", effect: "Increased risk of lactic acidosis" },
      { drug: "furosemide", severity: "mild", effect: "Furosemide increases metformin levels" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["GI upset", "diarrhea", "lactic acidosis (rare)", "B12 deficiency (chronic use)"],
  },
  {
    name: "lisinopril",
    genericName: "lisinopril",
    class: "ACE Inhibitor",
    indications: ["hypertension", "heart failure", "post-MI", "diabetic nephropathy"],
    contraindications: ["pregnancy", "bilateral renal artery stenosis", "history of angioedema", "hyperkalemia"],
    interactions: [
      { drug: "ibuprofen", severity: "moderate", effect: "Reduced antihypertensive effect; increased AKI risk (triple whammy)" },
      { drug: "potassium", severity: "moderate", effect: "Hyperkalemia risk" },
      { drug: "spironolactone", severity: "moderate", effect: "Hyperkalemia risk" },
      { drug: "furosemide", severity: "mild", effect: "Synergistic; risk of hypotension on initiation" },
      { drug: "aliskiren", severity: "contraindicated", effect: "Renal failure, hyperkalemia in diabetics" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["dry cough", "hyperkalemia", "angioedema", "AKI", "hypotension"],
  },
  {
    name: "atorvastatin",
    genericName: "atorvastatin calcium",
    class: "HMG-CoA Reductase Inhibitor (Statin)",
    indications: ["hyperlipidemia", "primary prevention CVD", "secondary prevention CVD"],
    contraindications: ["active liver disease", "pregnancy", "breastfeeding"],
    interactions: [
      { drug: "clarithromycin", severity: "severe", effect: "CYP3A4 inhibition; rhabdomyolysis risk" },
      { drug: "erythromycin", severity: "severe", effect: "CYP3A4 inhibition; rhabdomyolysis risk" },
      { drug: "grapefruit juice", severity: "moderate", effect: "Increased statin levels" },
      { drug: "warfarin", severity: "mild", effect: "Possible INR elevation" },
      { drug: "amiodarone", severity: "moderate", effect: "Increased myopathy risk" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["myalgia", "elevated transaminases", "rhabdomyolysis (rare)", "new-onset diabetes"],
  },
  {
    name: "ibuprofen",
    genericName: "ibuprofen",
    class: "NSAID",
    indications: ["pain", "inflammation", "fever", "dysmenorrhea"],
    contraindications: ["active GI bleeding", "severe heart failure", "severe renal impairment", "third trimester pregnancy"],
    interactions: [
      { drug: "lisinopril", severity: "moderate", effect: "Reduced antihypertensive effect; AKI risk" },
      { drug: "furosemide", severity: "moderate", effect: "Reduced diuretic effect; AKI risk" },
      { drug: "aspirin", severity: "moderate", effect: "Reduces aspirin's antiplatelet effect; GI bleeding" },
      { drug: "warfarin", severity: "severe", effect: "GI bleeding risk" },
      { drug: "methotrexate", severity: "severe", effect: "Methotrexate toxicity" },
    ],
    renalDosing: true,
    hepaticDosing: true,
    sideEffects: ["GI bleeding", "AKI", "hypertension", "fluid retention", "hepatotoxicity (rare)"],
  },
  {
    name: "amlodipine",
    genericName: "amlodipine besylate",
    class: "Dihydropyridine Calcium Channel Blocker",
    indications: ["hypertension", "stable angina", "vasospastic angina"],
    contraindications: ["severe hypotension", "severe aortic stenosis"],
    interactions: [
      { drug: "simvastatin", severity: "moderate", effect: "Increased simvastatin levels; limit simvastatin 20mg" },
      { drug: "clarithromycin", severity: "moderate", effect: "Increased amlodipine levels; hypotension" },
      { drug: "grapefruit juice", severity: "mild", effect: "Mild interaction" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["peripheral edema", "flushing", "headache", "dizziness"],
  },
  {
    name: "omeprazole",
    genericName: "omeprazole",
    class: "Proton Pump Inhibitor",
    indications: ["GERD", "peptic ulcer disease", "H. pylori eradication", "Zollinger-Ellison"],
    contraindications: ["hypersensitivity to PPIs"],
    interactions: [
      { drug: "clopidogrel", severity: "moderate", effect: "Reduced clopidogrel activation via CYP2C19" },
      { drug: "methotrexate", severity: "moderate", effect: "Increased methotrexate levels" },
      { drug: "warfarin", severity: "mild", effect: "INR elevation possible" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["headache", "diarrhea", "B12 deficiency (chronic use)", "fracture risk", "C. difficile risk"],
  },
  {
    name: "aspirin",
    genericName: "acetylsalicylic acid",
    class: "Antiplatelet / NSAID",
    indications: ["secondary prevention CVD", "ACS", "stroke prevention", "pain"],
    contraindications: ["active GI bleeding", "hemorrhagic stroke", "severe asthma (some)", "children with viral illness (Reye)"],
    interactions: [
      { drug: "warfarin", severity: "severe", effect: "Major bleeding risk" },
      { drug: "ibuprofen", severity: "moderate", effect: "Reduced cardioprotective effect" },
      { drug: "clopidogrel", severity: "mild", effect: "DAPT - dual antiplatelet; expected combination" },
      { drug: "methotrexate", severity: "moderate", effect: "Methotrexate toxicity" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["GI bleeding", "tinnitus (high dose)", "bronchospasm", "Reye syndrome"],
  },
  {
    name: "furosemide",
    genericName: "furosemide",
    class: "Loop Diuretic",
    indications: ["heart failure", "edema", "hypertension", "hyperkalemia"],
    contraindications: ["anuria", "severe hypovolemia", "sulfonamide hypersensitivity"],
    interactions: [
      { drug: "lisinopril", severity: "mild", effect: "Synergistic hypotension on initiation" },
      { drug: "ibuprofen", severity: "moderate", effect: "Reduced diuretic effect; AKI risk" },
      { drug: "lithium", severity: "severe", effect: "Lithium toxicity" },
      { drug: "digoxin", severity: "moderate", effect: "Digoxin toxicity from hypokalemia" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["hyponatremia", "hypokalemia", "hypomagnesemia", "ototoxicity", "dehydration"],
  },
  {
    name: "ceftriaxone",
    genericName: "ceftriaxone sodium",
    class: "Third-Generation Cephalosporin",
    indications: ["bacterial meningitis", "pneumonia", "UTI", "gonorrhea", "sepsis"],
    contraindications: ["severe penicillin allergy (anaphylaxis)", "neonates with hyperbilirubinemia"],
    interactions: [
      { drug: "calcium IV", severity: "contraindicated", effect: "Precipitation; fatal in neonates" },
      { drug: "warfarin", severity: "moderate", effect: "INR elevation" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["diarrhea", "rash", "C. difficile", "gallbladder sludging"],
  },
  {
    name: "vancomycin",
    genericName: "vancomycin",
    class: "Glycopeptide Antibiotic",
    indications: ["MRSA infections", "meningitis (empiric)", "C. difficile (oral)", "endocarditis"],
    contraindications: ["hypersensitivity"],
    interactions: [
      { drug: "gentamicin", severity: "moderate", effect: "Increased nephrotoxicity" },
      { drug: "furosemide", severity: "moderate", effect: "Increased ototoxicity" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["nephrotoxicity", "red man syndrome", "ototoxicity"],
  },
  {
    name: "dexamethasone",
    genericName: "dexamethasone",
    class: "Glucocorticoid",
    indications: ["bacterial meningitis (adjunct)", "cerebral edema", "asthma", "COPD exacerbation"],
    contraindications: ["systemic fungal infection (untreated)"],
    interactions: [
      { drug: "warfarin", severity: "moderate", effect: "Altered INR" },
      { drug: "rifampin", severity: "moderate", effect: "Reduced dexamethasone levels" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["hyperglycemia", "immunosuppression", "mood changes", "hypertension"],
  },
  {
    name: "methimazole",
    genericName: "methimazole",
    class: "Antithyroid (Thionamide)",
    indications: ["hyperthyroidism", "Graves disease", "thyroid storm"],
    contraindications: ["severe hepatic impairment", "agranulocytosis history", "first trimester pregnancy"],
    interactions: [
      { drug: "warfarin", severity: "moderate", effect: "Reduced anticoagulant effect" },
      { drug: "digoxin", severity: "mild", effect: "Reduced digoxin levels in euthyroid state" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["agranulocytosis", "hepatotoxicity", "rash", "arthralgia"],
  },
  {
    name: "propranolol",
    genericName: "propranolol hydrochloride",
    class: "Non-selective Beta-blocker",
    indications: ["hyperthyroidism (symptomatic)", "hypertension", "migraine prophylaxis", "essential tremor"],
    contraindications: ["severe asthma", "decompensated heart failure", "second/third degree AV block"],
    interactions: [
      { drug: "verapamil", severity: "severe", effect: "Bradycardia, AV block" },
      { drug: "insulin", severity: "moderate", effect: "Masks hypoglycemia symptoms" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["bradycardia", "fatigue", "bronchospasm", "depression"],
  },
  {
    name: "ursodeoxycholic acid",
    genericName: "ursodiol",
    class: "Bile Acid",
    indications: ["primary biliary cholangitis", "gallstone dissolution", "cholestasis of pregnancy"],
    contraindications: ["complete biliary obstruction", "calcified gallstones"],
    interactions: [
      { drug: "cholestyramine", severity: "moderate", effect: "Reduced absorption" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["diarrhea", "pruritus"],
  },
  {
    name: "warfarin",
    genericName: "warfarin sodium",
    class: "Vitamin K Antagonist (Anticoagulant)",
    indications: ["atrial fibrillation", "DVT/PE", "mechanical valve"],
    contraindications: ["active bleeding", "pregnancy", "recent surgery"],
    interactions: [
      { drug: "aspirin", severity: "severe", effect: "Major bleeding" },
      { drug: "amiodarone", severity: "severe", effect: "INR elevation" },
      { drug: "clarithromycin", severity: "severe", effect: "INR elevation" },
      { drug: "ibuprofen", severity: "severe", effect: "Bleeding risk" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["bleeding", "skin necrosis", "purple toe syndrome"],
  },
  {
    name: "clarithromycin",
    genericName: "clarithromycin",
    class: "Macrolide Antibiotic",
    indications: ["H. pylori", "atypical pneumonia", "skin infections"],
    contraindications: ["history of QT prolongation", "concurrent use with simvastatin"],
    interactions: [
      { drug: "atorvastatin", severity: "severe", effect: "Rhabdomyolysis" },
      { drug: "simvastatin", severity: "contraindicated", effect: "Rhabdomyolysis" },
      { drug: "warfarin", severity: "severe", effect: "INR elevation" },
      { drug: "amlodipine", severity: "moderate", effect: "Increased levels, hypotension" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["GI upset", "QT prolongation", "taste disturbance"],
  },
  {
    name: "clopidogrel",
    genericName: "clopidogrel bisulfate",
    class: "P2Y12 Inhibitor (Antiplatelet)",
    indications: ["ACS", "post-PCI", "stroke prevention"],
    contraindications: ["active bleeding", "severe hepatic impairment"],
    interactions: [
      { drug: "omeprazole", severity: "moderate", effect: "Reduced activation; consider pantoprazole" },
      { drug: "aspirin", severity: "mild", effect: "DAPT - expected combination" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["bleeding", "TTP (rare)"],
  },
  {
    name: "amoxicillin",
    genericName: "amoxicillin",
    class: "Aminopenicillin",
    indications: ["otitis media", "pneumonia", "UTI", "H. pylori"],
    contraindications: ["penicillin allergy"],
    interactions: [
      { drug: "warfarin", severity: "moderate", effect: "INR elevation" },
      { drug: "methotrexate", severity: "moderate", effect: "Methotrexate toxicity" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["diarrhea", "rash", "anaphylaxis (with allergy)"],
  },
  {
    name: "insulin",
    genericName: "insulin (various)",
    class: "Hormone (Antidiabetic)",
    indications: ["type 1 diabetes", "type 2 diabetes", "DKA", "hyperkalemia"],
    contraindications: ["hypoglycemia"],
    interactions: [
      { drug: "propranolol", severity: "moderate", effect: "Masks hypoglycemia" },
      { drug: "glucocorticoids", severity: "moderate", effect: "Hyperglycemia counteraction" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["hypoglycemia", "weight gain", "lipodystrophy"],
  },
  {
    name: "heparin",
    genericName: "heparin sodium",
    class: "Anticoagulant",
    indications: ["DVT/PE", "ACS", "bridging anticoagulation"],
    contraindications: ["active bleeding", "HIT history"],
    interactions: [
      { drug: "aspirin", severity: "severe", effect: "Major bleeding" },
      { drug: "clopidogrel", severity: "severe", effect: "Major bleeding" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["bleeding", "HIT", "osteoporosis"],
  },
  {
    name: "nitroglycerin",
    genericName: "nitroglycerin",
    class: "Nitrate",
    indications: ["angina", "ACS", "acute pulmonary edema"],
    contraindications: ["sildenafil within 24h", "severe hypotension", "inferior MI with RV involvement"],
    interactions: [
      { drug: "sildenafil", severity: "contraindicated", effect: "Severe hypotension" },
      { drug: "tadalafil", severity: "contraindicated", effect: "Severe hypotension" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["headache", "hypotension", "flushing"],
  },
  {
    name: "morphine",
    genericName: "morphine sulfate",
    class: "Opioid",
    indications: ["severe pain", "ACS", "acute pulmonary edema"],
    contraindications: ["respiratory depression", "paralytic ileus", "head trauma (relative)"],
    interactions: [
      { drug: "benzodiazepines", severity: "severe", effect: "Respiratory depression" },
      { drug: "MAOIs", severity: "severe", effect: "Serotonin syndrome" },
    ],
    renalDosing: true,
    hepaticDosing: true,
    sideEffects: ["respiratory depression", "constipation", "nausea", "sedation"],
  },
  {
    name: "spironolactone",
    genericName: "spironolactone",
    class: "Aldosterone Antagonist",
    indications: ["heart failure", "hypertension", "cirrhosis ascites", "hyperaldosteronism"],
    contraindications: ["hyperkalemia", "anuria", "Addison's disease"],
    interactions: [
      { drug: "lisinopril", severity: "moderate", effect: "Hyperkalemia" },
      { drug: "potassium", severity: "severe", effect: "Hyperkalemia" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["hyperkalemia", "gynecomastia", "AKI"],
  },
  {
    name: "metoprolol",
    genericName: "metoprolol tartrate",
    class: "Cardioselective Beta-blocker",
    indications: ["hypertension", "heart failure", "ACS", "atrial fibrillation"],
    contraindications: ["severe bradycardia", "decompensated HF", "high-grade AV block"],
    interactions: [
      { drug: "verapamil", severity: "severe", effect: "Bradycardia, heart block" },
      { drug: "insulin", severity: "moderate", effect: "Masks hypoglycemia" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["bradycardia", "fatigue", "hypotension"],
  },
  {
    name: "levothyroxine",
    genericName: "levothyroxine sodium",
    class: "Thyroid Hormone",
    indications: ["hypothyroidism", "thyroid cancer (suppression)"],
    contraindications: ["untreated adrenal insufficiency", "acute MI"],
    interactions: [
      { drug: "calcium", severity: "moderate", effect: "Reduced absorption" },
      { drug: "omeprazole", severity: "mild", effect: "Reduced absorption" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["palpitations", "weight loss (overdose)", "anxiety"],
  },
  {
    name: "simvastatin",
    genericName: "simvastatin",
    class: "Statin",
    indications: ["hyperlipidemia"],
    contraindications: ["active liver disease", "pregnancy"],
    interactions: [
      { drug: "clarithromycin", severity: "contraindicated", effect: "Rhabdomyolysis" },
      { drug: "amlodipine", severity: "moderate", effect: "Limit simvastatin 20mg" },
      { drug: "grapefruit juice", severity: "severe", effect: "Increased levels" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["myalgia", "rhabdomyolysis", "hepatotoxicity"],
  },
  {
    name: "enoxaparin",
    genericName: "enoxaparin sodium",
    class: "Low Molecular Weight Heparin",
    indications: ["VTE prophylaxis", "DVT/PE treatment", "ACS"],
    contraindications: ["active bleeding", "HIT history", "severe renal impairment"],
    interactions: [
      { drug: "aspirin", severity: "moderate", effect: "Bleeding" },
      { drug: "warfarin", severity: "severe", effect: "Bleeding" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["bleeding", "thrombocytopenia"],
  },
  {
    name: "atenolol",
    genericName: "atenolol",
    class: "Cardioselective Beta-blocker",
    indications: ["hypertension", "angina", "hyperthyroidism"],
    contraindications: ["severe bradycardia", "high-grade AV block"],
    interactions: [
      { drug: "verapamil", severity: "severe", effect: "Bradycardia" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["bradycardia", "fatigue", "cold extremities"],
  },
  {
    name: "ramipril",
    genericName: "ramipril",
    class: "ACE Inhibitor",
    indications: ["hypertension", "heart failure", "diabetic nephropathy"],
    contraindications: ["pregnancy", "bilateral renal artery stenosis", "history of angioedema"],
    interactions: [
      { drug: "ibuprofen", severity: "moderate", effect: "AKI, reduced effect" },
      { drug: "potassium", severity: "moderate", effect: "Hyperkalemia" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["dry cough", "angioedema", "hyperkalemia"],
  },
  {
    name: "azithromycin",
    genericName: "azithromycin",
    class: "Macrolide",
    indications: ["respiratory infections", "STIs"],
    contraindications: ["history of cholestatic jaundice with macrolide"],
    interactions: [
      { drug: "warfarin", severity: "moderate", effect: "INR elevation" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["GI upset", "QT prolongation"],
  },
  {
    name: "carbimazole",
    genericName: "carbimazole",
    class: "Antithyroid (Thionamide)",
    indications: ["hyperthyroidism"],
    contraindications: ["severe hepatic impairment"],
    interactions: [
      { drug: "warfarin", severity: "moderate", effect: "Altered INR" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["agranulocytosis", "rash", "hepatotoxicity"],
  },
  {
    name: "propylthiouracil",
    genericName: "propylthiouracil",
    class: "Antithyroid (Thionamide)",
    indications: ["hyperthyroidism (first trimester pregnancy)", "thyroid storm"],
    contraindications: ["severe hepatic impairment"],
    interactions: [
      { drug: "warfarin", severity: "moderate", effect: "Altered INR" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["agranulocytosis", "hepatotoxicity", "vasculitis"],
  },
  {
    name: "pantoprazole",
    genericName: "pantoprazole sodium",
    class: "Proton Pump Inhibitor",
    indications: ["GERD", "peptic ulcer disease"],
    contraindications: ["hypersensitivity to PPIs"],
    interactions: [
      { drug: "methotrexate", severity: "moderate", effect: "Increased levels" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["headache", "diarrhea", "B12 deficiency", "fracture risk"],
  },
  {
    name: "piperacillin-tazobactam",
    genericName: "piperacillin/tazobactam",
    class: "Penicillin/Beta-lactamase Inhibitor",
    indications: ["sepsis", "intra-abdominal infections", "pneumonia"],
    contraindications: ["penicillin allergy"],
    interactions: [
      { drug: "vancomycin", severity: "moderate", effect: "Increased AKI risk" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["diarrhea", "rash", "AKI"],
  },
  {
    name: "acetaminophen",
    genericName: "acetaminophen",
    class: "Analgesic / Antipyretic",
    indications: ["pain", "fever"],
    contraindications: ["severe hepatic impairment", "G6PD deficiency"],
    interactions: [
      { drug: "warfarin", severity: "mild", effect: "Possible INR elevation with chronic use" },
      { drug: "alcohol", severity: "moderate", effect: "Hepatotoxicity" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["hepatotoxicity (overdose)", "rash (rare)"],
  },
  {
    name: "ondansetron",
    genericName: "ondansetron",
    class: "5-HT3 Antagonist (Antiemetic)",
    indications: ["nausea/vomiting"],
    contraindications: ["congenital long QT", "concurrent apomorphine"],
    interactions: [
      { drug: "tramadol", severity: "moderate", effect: "Serotonin syndrome" },
      { drug: "QT-prolonging drugs", severity: "moderate", effect: "QT prolongation" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["constipation", "headache", "QT prolongation"],
  },
  {
    name: "digoxin",
    genericName: "digoxin",
    class: "Cardiac Glycoside",
    indications: ["heart failure", "atrial fibrillation"],
    contraindications: ["AV block", "ventricular fibrillation"],
    interactions: [
      { drug: "furosemide", severity: "moderate", effect: "Hypokalemia leads to digoxin toxicity" },
      { drug: "amiodarone", severity: "severe", effect: "Increased digoxin levels" },
      { drug: "verapamil", severity: "severe", effect: "Increased digoxin levels" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["nausea", "arrhythmia", "visual disturbance (yellow halo)"],
  },
  {
    name: "amiodarone",
    genericName: "amiodarone hydrochloride",
    class: "Class III Antiarrhythmic",
    indications: ["ventricular arrhythmia", "atrial fibrillation"],
    contraindications: ["severe sinus node dysfunction", "high-grade AV block", "iodine allergy"],
    interactions: [
      { drug: "warfarin", severity: "severe", effect: "Marked INR elevation" },
      { drug: "digoxin", severity: "severe", effect: "Digoxin toxicity" },
      { drug: "simvastatin", severity: "moderate", effect: "Myopathy risk" },
    ],
    renalDosing: false,
    hepaticDosing: true,
    sideEffects: ["pulmonary fibrosis", "hypothyroidism", "hyperthyroidism", "corneal deposits", "hepatotoxicity"],
  },
  {
    name: "ciprofloxacin",
    genericName: "ciprofloxacin",
    class: "Fluoroquinolone",
    indications: ["UTI", "GI infections", "respiratory infections"],
    contraindications: ["tendon disorders", "QT prolongation"],
    interactions: [
      { drug: "warfarin", severity: "moderate", effect: "INR elevation" },
      { drug: "theophylline", severity: "severe", effect: "Theophylline toxicity" },
    ],
    renalDosing: true,
    hepaticDosing: false,
    sideEffects: ["tendon rupture", "QT prolongation", "C. difficile", "neuropathy"],
  },
  {
    name: "prednisone",
    genericName: "prednisone",
    class: "Glucocorticoid",
    indications: ["inflammation", "autoimmune disease", "asthma"],
    contraindications: ["systemic fungal infection"],
    interactions: [
      { drug: "ibuprofen", severity: "moderate", effect: "GI bleeding risk" },
      { drug: "warfarin", severity: "moderate", effect: "Altered INR" },
    ],
    renalDosing: false,
    hepaticDosing: false,
    sideEffects: ["hyperglycemia", "osteoporosis", "Cushing features", "immunosuppression"],
  },
];

export function getDrug(name: string): Drug | undefined {
  const lower = name.toLowerCase();
  return MOCK_DRUGS.find(
    (d) => d.name.toLowerCase() === lower || d.genericName.toLowerCase() === lower
  );
}
